import type { DecisionTemplate } from './types';

export const PERSONAL_DECISION_CHECKLIST = [
  'reversibility（可逆性）',
  'regret test（后悔最小化）',
  'downside floor（最坏情况）',
  'opportunity cost（机会成本）',
  'pre-mortem（事前验尸）',
];

export const DECISION_TEMPLATES: DecisionTemplate[] = [
  {
    id: 'offer-choice',
    label: 'Offer 选择',
    description: '适合比较多个 offer，强调成长、现金流、城市与风险的综合取舍。',
    family: 'career',
    decisionType: 'career',
    desiredOutput: 'recommendation',
    verificationProfileId: 'career_offer',
    evidenceExpectations: [
      'offer 薪酬、股票、bonus 与签约期限',
      '工作地点、remote/hybrid 政策',
      '团队职责、汇报关系、试用期或 relocation 条款',
      '公司近期业务与裁员/扩张信号',
    ],
    reviewWindowSuggestion: '入职后 30 天与 90 天各复盘一次。',
    defaultRedLines: [
      '现金流或税后收入低于底线',
      '岗位职责与承诺严重不一致',
      '工作强度或通勤超过可接受范围',
    ],
    defaultRevisitTriggers: [
      '薪酬、职级或汇报线发生变化',
      '团队负责人离职或业务方向大改',
      '签约截止日前出现更优备选',
    ],
    goal: '在多个工作机会之间做出短中长期都说得通的选择。',
    background: '请补充你的当前阶段、手上 offer、顾虑和期望的成长路径。',
    constraints: '收入底线、城市偏好、工作强度、长期方向、家庭因素。',
    focalQuestions: '哪份 offer 在当前阶段最值得接？为什么不是其他选项？',
    requiredDimensions:
      '总包与现金流、成长曲线、业务质量、团队质量、城市与通勤、机会成本、可逆性、最坏情况、pre-mortem。',
    analysisChecklist: PERSONAL_DECISION_CHECKLIST,
  },
  {
    id: 'career-pivot',
    label: '职业转向',
    description: '适合评估跨职能、跨行业、读书转型或创业前的路径切换。',
    family: 'career',
    decisionType: 'career',
    desiredOutput: 'action_plan',
    verificationProfileId: 'career_company_research',
    evidenceExpectations: [
      '目标岗位或行业的真实 JD 与能力要求',
      '转型成本、学习周期与机会窗口',
      '公司或行业对背景门槛的明确表述',
      '替代路径和过渡方案的可行性',
    ],
    reviewWindowSuggestion: '启动转型后 45 天复盘一次，确认是否继续投入。',
    defaultRedLines: [
      '转型成本超过现金流承受范围',
      '关键能力缺口在目标窗口内无法补齐',
      '转型后最坏情形不可接受',
    ],
    defaultRevisitTriggers: [
      '出现低成本试水机会',
      '目标行业招聘信号显著变化',
      '当前岗位出现超预期成长空间',
    ],
    goal: '评估是否值得为下一阶段职业方向做一次显著转向。',
    background: '请补充当前岗位、想转向的方向、已有准备与顾虑。',
    constraints: '时间成本、收入波动、学习曲线、家庭/地点约束、试错窗口。',
    focalQuestions: '现在转向是否值得？最低风险的试水路径是什么？',
    requiredDimensions:
      '转型成本、回报上限、试水路径、机会成本、可逆性、后悔成本、最坏情况、pre-mortem。',
    analysisChecklist: PERSONAL_DECISION_CHECKLIST,
  },
  {
    id: 'move-city',
    label: '迁居换城',
    description: '适合在多个城市之间比较职业、生活成本、关系网络与长期稳定性。',
    family: 'life',
    decisionType: 'life',
    desiredOutput: 'recommendation',
    verificationProfileId: 'life_location_policy',
    evidenceExpectations: [
      '城市政策、落户/签证/居留规则',
      '租住成本、通勤和基本生活成本',
      '工作机会密度与支持网络',
      '学校、医疗或家庭相关约束',
    ],
    reviewWindowSuggestion: '迁居前 2 周再核验一次，迁居后 60 天复盘体验。',
    defaultRedLines: [
      '生活成本显著超出预算',
      '关键政策门槛不满足',
      '支持网络过弱且最坏情况难兜底',
    ],
    defaultRevisitTriggers: [
      '目标城市政策变化',
      '新的工作或住房条件出现',
      '家庭因素或照护需求变化',
    ],
    goal: '判断是否该迁居，以及哪座城市更匹配当前阶段。',
    background: '请补充当前城市、候选城市、迁居动机和主要顾虑。',
    constraints: '预算、家庭因素、工作机会、签证/户籍/政策、心理承受力。',
    focalQuestions: '搬去哪里最合理？不搬的机会成本是什么？',
    requiredDimensions:
      '成本、机会、关系网络、政策门槛、可逆性、后悔最小化、最坏情况、pre-mortem。',
    analysisChecklist: PERSONAL_DECISION_CHECKLIST,
  },
  {
    id: 'rent-vs-buy',
    label: '租房还是买房',
    description: '适合比较租与买的现金流、居住稳定性和灵活性。',
    family: 'life',
    decisionType: 'life',
    desiredOutput: 'comparison',
    verificationProfileId: 'life_housing',
    evidenceExpectations: [
      '房价或租金、税费、首付与月供',
      '通勤、学区或生活半径',
      '维护成本、流动性与政策限制',
      '未来 2-5 年居住计划与现金流压力',
    ],
    reviewWindowSuggestion: '关键房源或政策变化时立即复盘，否则每月复盘一次。',
    defaultRedLines: [
      '月供或总持有成本挤压安全现金流',
      '需要承担无法接受的流动性风险',
      '核心需求如通勤/学区无法满足',
    ],
    defaultRevisitTriggers: [
      '利率或首付政策明显变化',
      '出现更优房源或租住方案',
      '家庭结构或工作城市发生变化',
    ],
    goal: '比较租住与购置哪条路径更适合当前生活阶段。',
    background: '请补充预算、家庭规划、居住年限和候选区域。',
    constraints: '首付能力、月供上限、流动性需求、工作地点、家庭需求。',
    focalQuestions: '买带来的确定性是否值得支付灵活性成本？',
    requiredDimensions:
      '现金流、总成本、灵活性、居住质量、政策风险、机会成本、可逆性、最坏情况、pre-mortem。',
    analysisChecklist: PERSONAL_DECISION_CHECKLIST,
  },
  {
    id: 'investment-allocation',
    label: '资产配置',
    description: '适合在多种资产之间做仓位配置与风险预算决策。',
    family: 'money',
    decisionType: 'investment',
    desiredOutput: 'recommendation',
    verificationProfileId: 'money_investment_product',
    evidenceExpectations: [
      '费用、锁定期、流动性与税务影响',
      '产品风险披露与历史表现时间点',
      '配置与目标期限、回撤承受能力是否匹配',
      '替代产品的成本和机会成本',
    ],
    reviewWindowSuggestion: '建立仓位后按月小复盘，按季度复盘 thesis。',
    defaultRedLines: [
      '最大回撤超出可接受范围',
      '流动性与未来资金计划冲突',
      '关键风险无法通过分散或仓位控制缓释',
    ],
    defaultRevisitTriggers: [
      '费用、政策或产品条款变化',
      '核心 thesis 被市场或基本面证伪',
      '现金流需求和期限发生变化',
    ],
    goal: '在收益目标与风险承受能力之间找到更稳健的资产配置方案。',
    background: '请补充当前资产、期限、风险偏好、已有配置与担忧。',
    constraints: '回撤承受力、资金用途、流动性、税务、账户限制。',
    focalQuestions: '怎样的配置更匹配当前目标，而不是短期情绪？',
    requiredDimensions:
      '预期收益、下行风险、费用、流动性、相关性、机会成本、可逆性、最坏情况、pre-mortem。',
    analysisChecklist: PERSONAL_DECISION_CHECKLIST,
  },
  {
    id: 'large-purchase',
    label: '大额购买',
    description: '适合车、设备、课程或长期服务等高成本购买决策。',
    family: 'money',
    decisionType: 'general',
    desiredOutput: 'action_plan',
    verificationProfileId: 'money_large_purchase',
    evidenceExpectations: [
      '价格、融资、保修和退货条款',
      '交付、安装、运输或售后限制',
      '替代方案与二手/租赁比较',
      '使用频率、残值和后悔概率',
    ],
    reviewWindowSuggestion: '购买前 48 小时冷静期，购买后 30 天复盘效用。',
    defaultRedLines: [
      '购买后影响应急现金储备',
      '售后、退换或保修条件不透明',
      '使用频率不足以支撑成本',
    ],
    defaultRevisitTriggers: [
      '价格或促销条件变化',
      '发现更低成本替代方案',
      '使用场景或预算发生变化',
    ],
    goal: '判断这笔大额支出是否值得，以及用什么方式买更划算。',
    background: '请补充商品/服务、预算、候选方案和当前使用需求。',
    constraints: '预算、现金流、使用频率、售后要求、家庭协同。',
    focalQuestions: '现在买是否合理？买哪种方案最不容易后悔？',
    requiredDimensions:
      '总成本、使用价值、售后与条款、残值、替代方案、机会成本、可逆性、最坏情况、pre-mortem。',
    analysisChecklist: PERSONAL_DECISION_CHECKLIST,
  },
];
