import type { DecisionTemplate } from './types';

export const DECISION_TEMPLATES: DecisionTemplate[] = [
  {
    id: 'investment-thesis',
    label: '投资判断',
    description: '适合股票、基金、资产配置和仓位判断。',
    decisionType: 'investment',
    desiredOutput: 'recommendation',
    goal: '判断是否值得投入资金，以及以什么前提和节奏进入。',
    background: '请补充资产、期限、仓位约束、已有判断。',
    constraints: '风险承受能力、资金规模、可接受回撤、流动性需求。',
    focalQuestions: '当前机会来自哪里？主要风险是什么？最关键的验证点是什么？',
    requiredDimensions: '收益空间、风险、时间窗口、估值、反例、退出条件。',
  },
  {
    id: 'product-direction',
    label: '产品方案选择',
    description: '适合做功能路线、版本优先级和方案取舍。',
    decisionType: 'product',
    desiredOutput: 'comparison',
    goal: '在多个产品方案之间做出优先级和方向选择。',
    background: '请补充用户、场景、业务目标、已有方案。',
    constraints: '时间、人力、技术债、上线窗口、关键依赖。',
    focalQuestions: '最值得做的方案是什么？为什么不是其他方案？',
    requiredDimensions: '用户价值、商业价值、实现成本、风险、可验证性。',
  },
  {
    id: 'career-choice',
    label: '职业选择',
    description: '适合 offer、方向、岗位与成长路径比较。',
    decisionType: 'career',
    desiredOutput: 'recommendation',
    goal: '在多个职业方向或机会之间做出理性选择。',
    background: '请补充你的阶段、目标、备选方案和顾虑。',
    constraints: '收入、成长速度、城市、工作强度、长期路径。',
    focalQuestions: '哪条路径更适合当前阶段？短中长期分别意味着什么？',
    requiredDimensions: '成长性、机会成本、风险、匹配度、复利空间。',
  },
  {
    id: 'life-planning',
    label: '生活规划',
    description: '适合重要生活决策，例如迁居、购房、关系与家庭安排。',
    decisionType: 'life',
    desiredOutput: 'action_plan',
    goal: '为生活中的重要选择形成更清晰的取舍和行动计划。',
    background: '请补充当前处境、候选方案、担忧和希望达成的状态。',
    constraints: '预算、时间、家庭因素、地点限制、心理负担。',
    focalQuestions: '这个决定真正要解决的核心问题是什么？',
    requiredDimensions: '成本、收益、情绪影响、长期稳定性、可逆性。',
  },
  {
    id: 'risk-review',
    label: '风险评估',
    description: '适合先识别关键风险，再决定是否推进。',
    decisionType: 'risk',
    desiredOutput: 'risk_assessment',
    goal: '识别核心风险并明确应对动作，再决定是否推进。',
    background: '请补充项目、计划或选择的上下文。',
    constraints: '时间、资源、容错率、不可承受后果。',
    focalQuestions: '最可能出问题的地方在哪里？触发信号是什么？',
    requiredDimensions: '概率、影响、预警信号、缓解方案、兜底方案。',
  },
];
